orchidsoftware/platform

- resources/views/fields/tinymce.blade.php
Javascript Error:  Uncaught SyntaxError: Unexpected token )
У меня почему-то не работает TinyMCE с этой запятой.
> Fix javascript error in TinyMCE

- resources/views/container/posts/main.blade.php
- resources/views/container/systems/category/grid.blade.php
- resources/views/container/systems/comment/grid.blade.php
- resources/views/container/systems/roles/grid.blade.php
- resources/views/container/systems/users/grid.blade.php
Поправил пагинацию в ролях, пользователях, категориях, комментариях, постах. Вроде больше негде.
Было "показано 560 -15 из 15 элементов" на всех 38 страницах, а на последней "показано 560 -15 из 5 элементов"
Стало "показано 31 - 45 из 560 элементов" на 3 из 38 страниц, а на последней "показано 556 - 560 из 560 элементов"
> Fix paginations

- resources/views/container/systems/category/info.blade.php
- src/Platform/Forms/Form.php
- src/Platform/Http/Controllers/Systems/CategoryController.php
- src/Platform/Http/Forms/Category/CategoryDescForm.php
- src/Platform/Http/Forms/Category/CategoryMainForm.php
- Form.php добавлены методы `validationMessages() : array` и `validationCustomAttributes() : array`, для передачи в валидатор своих сообщений
- info.blade.php при ошибке при создании записи не возвращалось введенное значение slug
- CategoryController в методе `store(...)` вместо `back()` - `redirect()` на страницу редактирования созданной записи
- CategoryMainForm - исправлены правила валидации добавлена валидация второй формы; наименования атрибутов в валидацию; нормализация slug перед сохранением.
- CategoryDescForm - исправлены правила валидации убрана проверка уникальности slug, т.к. она выполняется в CategoryMainForm; наименования атрибутов в валидацию; нормализация slug перед сохранением.
> Сохранение разделов

- src/Screen/Fields/Select.php
При создании такого поля
```
Select::make('user.user_id')
->fromModel(User::class,'name','id')
->title('User'),
```
при загрузке, уже после того когда сохранен выдает ошибку
в переменной $item находится id пользователя, а не объект
Fixes #
-
-
-
> Fix error in select field

- src/Screen/Fields/DateTimer.php
eg.
```php
DateTimer::make('season.time')
->title('Time')
->noCalendar()
->format('h:i K'),
`
> Fields: added support of timepicker only for the datetimer field

- resources/views/fields/range.blade.php
Например если: $attributes['name']=options[date][range] 
символы [] не используются в id
> Ошибка если имя массив

- resources/views/app.blade.php
Необходимо для поддержки vue.js и любых других библиотек которые необходимо подключать внизу документа.
> Added defer for the scripts

- src/Screen/Fields/ViewField.php
This change removes the required value check for the template. 
This problem is described in the issue #970.
> refs #970 [Field] Fixed template requirement as attribute

- src/Filters/HttpFilter.php
- src/Platform/Commands/ChartCommand.php
- src/Platform/Commands/FilterCommand.php
- src/Platform/Commands/InstallCommand.php
- src/Platform/Commands/MetricsCommand.php
- src/Platform/Commands/RowsCommand.php
- src/Platform/Commands/ScreenCommand.php
- src/Platform/Commands/SelectionCommand.php
- src/Platform/Commands/TableCommand.php
- src/Platform/Dashboard.php
- src/Platform/Http/Screens/SearchScreen.php
- src/Platform/Providers/FoundationServiceProvider.php
- src/Platform/Providers/PlatformServiceProvider.php
- src/Platform/Providers/RouteServiceProvider.php
- src/Presets/Source.php
- src/Screen/Fields/ViewField.php
- src/Screen/TD.php
- src/Support/helpers.php
- tests/Environment.php
- tests/Exemplar/ExemplarServiceProvider.php
Added a new appeal:
```php
use Orchid\Platform\Dashboard;
// base usage
Dashboard::path();
// path to file
Dashboard::path('config/platform.php');
```
Handling through a constant is deprecated:
```php
$config = PLATFORM_PATH.'/config/platform.php';
```
> Changed path constant to a static method

- .gitignore
- resources/views/partials/notification.blade.php
Sometimes in notifications we need to show links. Now it can be done. All notification managing by developers then it should not create any problems with security.
> Added support of html in notifications. Usefull for the external links

- src/Platform/Http/Controllers/Systems/ResourceController.php
-  `DIRECTORY_SEPARATOR` in `ResourceController` fix, it will work correctly on Windows
> Not found resource for windows

- CHANGELOG.md
- Support Laravel 7.0 instead of 6.0 typo
> Fix changelog: Laravel 6.0 -> 7.0 typo

- CHANGELOG.md
- resources/views/dashboard.blade.php
- src/Platform/Dashboard.php
Fixed the behavior setting the maximum width for the name and description of the screen properties. Even if there are no buttons in the `CommandBar`, the name could not take its place.
> Removed the restriction of the length of the name in the screen

- phpunit.xml
- src/Support/Init.php
- tests/Unit/SupportFormatsTest.php
Fixes #
Убрана запятая в качестве разделителя разрядов из функции number_format(), которая стоит по умолчанию, иначе при привидении к числу, значения после первой запятой отбрасываются
> number format update

- database/migrations/2015_04_12_000000_create_orchid_users_table.php
- src/Access/UserAccess.php
- tests/Unit/PermissionTest.php
Fixes #
When trying to access the dashboard with an empty permissions field the error below is received, while setting a default ([] or {}) results in a 403 which is the expected behaviour
`Argument 1 passed to Orchid\Platform\Models\User::Orchid\Access\{closure}() must be of the type array, null given`
- add a default to the column
- check if `$this->cachePermissions` is null in `src/Access/UserAccess.php:77`
> add default to user permissions

- src/Screen/Fields/Select.php
- tests/Unit/Screen/Fields/SelectTest.php
by executing the query before plucking model attributes can be used as 'name' property
Fixes #
```php
Select::make('category.parent_id')
->title('Categoria padre')
->fromQuery(Category::byCurrentShop()->orderBy('path'), 'indented_name') // indented_name is magic attribute of Category (getIndentedNameAttribute),
```
- Execute the query and perform the pluck on models
> custom model attributes in selects

- src/Platform/Updates.php
Fixes #1093
Return statement was missing in `Cache::remember()` callback, so cache didn't work (effectively stored null value in cache).
I added the return statement.
> Fixes #1093 Updates::requestVersion() cache broken

- resources/views/layouts/modal.blade.php
- src/Screen/Layouts/Modal.php
- tests/App/Screens/ModalScreenWithoutButtons.php
- tests/Unit/Screen/ModalWithoutButtonTest.php
- tests/Unit/Screen/ModalWithoutButtonsTest.php
Regarding #1095 , this PR adds a new method called `withoutApplyButton()` to `Modal::class` so we can remove the apply button if needed
**update**
@tabuna suggested that it is valid to add this option to the close button too, so we have `withoutCloseButton()` along side `withoutApplyButton()`
> added withoutApplyButton to modal based layouts

- CHANGELOG.md
- config/platform.php
- src/Attachment/Attachable.php
- src/Attachment/Contracts/Engine.php
- src/Attachment/Engines/Generator.php
- src/Attachment/File.php
- tests/Unit/AttachmentTest.php
- tests/Unit/Engine/CustomAttachmentGenerator.php
This is an offer to add an intermediate class for uploading files. 
They will be responsible for the format of the created path and hash.
This should solve the problem of changing the path.
So, by default, paths are formed according to the schema:
```php
'.../Y/m/d/filename.jpg'
```
Now it is moved to a separate class, with the appropriate method:
```php
<?php
use Orchid\Attachment\Engines\Generator;
class CustomAttachmentGenerator extends Generator
{
public function path(): string
{
return 'custom';
}
}
```
After applying it, **new** paths will be created as follows:
```php
'.../custom/filename.jpg'
```
Another example of utility can be changing the generation of a hash of a file, for example:
```php
<?php
use Orchid\Attachment\Engines\Generator;
class CustomAttachmentGenerator extends …
```
> [Draft] Engine for attachment upload

- resources/views/partials/fields/groups.blade.php
- src/Screen/Builder.php
- src/Screen/Contracts/Groupable.php
- src/Screen/Field.php
- src/Screen/Fields/Group.php
This PR expands the possibilities of creating field groups by adding a new interface to the form builder.
**Columns occupy the entire width of the screen.**
```php
Group::make([
// ...
])->fullWidth();
```
**Columns only take up as much space as needed.**
```php
Group::make([
// ...
])->autoWidth();
```
Since the group is no longer tied to the form builder, it is only one more field that can be inherited or altered completely. That call to the base field class seems a little strange. I propose to declare it obsolete and delete it in the next major version
```php
Field::group([
// ...
]);
```
This breaks the undocumented ability to use an array in field returns, for example:
```php
Layout::rows([
[
// fields
],
]);
```
> [7.7] Added field group class

- src/Platform/Http/Controllers/Systems/AttachmentController.php
Since its is possible to exchange the Attachment class with a Model that could have a string primary we can't be sure id will be an int
> string id for attachment

- src/Platform/Dashboard.php
- tests/Unit/PermissionTest.php
Добавил тест подтверждающий это
Fixes #
Исправил удаление permission в Dashboard
Как я предпологал из этого [issue](https://github.com/orchidsoftware/platform/issues/634)
Удаляется просто permission
Может так же есть смысл, удалять все группу?
> Исправил удаление permission в Dashboard

- src/Screen/Contracts/Fieldable.php
Thanks to PhpStorm highlighted the problem
> Fix PHPDoc return type for Fieldable::get()

- resources/views/auth/passwords/reset.blade.php
- routes/auth.php
Adding a name to the route kpagos/password/reset to be used in the reset.blade form action param of the reset password form
Fixes #
when you get the link to your user email with the reset token and orchid displays the reset apssword form, after you correctly fill it and send it     platform redirectyou back again to the reset form and send a new reset pasword token as 
**the previusly action param is set to route('platform.password.email')  insead to a route that runs the reset method of ResetPasswordController**
-Add a name to the kpagos/password/reset route
-CHange the post action of the reset form on auth.password.reset.blade
> adding a name to the reset password route of auth group

- src/Platform/Http/Controllers/Auth/ForgotPasswordController.php
This is to further protect against username enumeration by not disclosing if the user exists in the database.
References:
* https://blog.rapid7.com/2017/06/15/about-user-enumeration/
* https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/03-Identity_Management_Testing/04-Testing_for_Account_Enumeration_and_Guessable_User_Account
> Override `sendResetLinkEmail` method to return success message in all cases

- src/Screen/Actions/Button.php
phpStan (PHP Static Analysis Tool) throws an error  #Call to an undefined method Orchid\\Screen\\Actions\\Button\:\:asyncParameters\(\)#, because phpDoc in method make declares to return Button, but code declares creating static class
> Update phpDoc in Button class

- resources/sass/app.scss
During the compilation on a fresh Laravel 8 installation, I ran into a not found error.
This fix the problem.
> Fix assets compilation

- resources/views/fields/cropper.blade.php
- src/Screen/Fields/Cropper.php
It's difficult to crop images if the modal closes when the user clicks outside the modal. I think it's a usability problem.
Add static to backdrop so the modal wouldn't close on click (https://getbootstrap.com/docs/4.4/components/modal/#options)
> Add static backdrop method to Cropper

- resources/js/controllers/fields/quill_controller.js
- resources/views/fields/quill.blade.php
- src/Screen/Fields/Quill.php
is not possible to change the Quill toolbar
- Give the option to add custom controls to Quill toolbar
- It allows the user to select 6 groups of controls
```javascript
Quill::make('quill')
->title('Quill')
->toolbar(["text", "color", "header", "list", "format", "media"])
```
> Add custom controls to Quill toolbar

- CHANGELOG.md
- src/Platform/Dashboard.php
- src/Platform/ItemMenu.php
- src/Platform/Providers/FoundationServiceProvider.php
- Use route arguments when generating an active link
- Wait for a call to the breadcrumbs service before your ad.
> ## 9.0.2 - 2020-10-02

- resources/views/partials/filters/date.blade.php
- resources/views/partials/filters/numeric.blade.php
- resources/views/partials/filters/text.blade.php
> refs #1145 Fixed filters overlay for table

- resources/views/partials/layouts/td.blade.php
- tests/Unit/Screen/TDForTableTest.php
- Redundant rendering of attribute `style` with an empty value `width` when `width` is empty in the template `td`
> Fixed rendering of attribute style in td view

- resources/views/partials/layouts/td.blade.php
- tests/Unit/Screen/TDForTableTest.php
- Use `is_numeric` instead `ctype_digit` to determine if a variable is a number
`ctype_digit` behaves incorrectly when we pass, for example, a value of type `integer` since this method can interpret numbers as `ASCII` characters. Also, the method does not interpret floating values as numbers. 
https://www.php.net/manual/en/function.ctype-digit.php#refsect1-function.ctype-digit-examples
As a result, the value is obtained without the ending `px` and is essentially incorrect.
It is a good idea to use the `is_numeric` method, which is more flexible and correct in determining whether a variable is a number or not.
https://www.php.net/manual/en/function.is-numeric.php#refsect1-function.is-numeric-examples
- Test cases
> Fixed generate td css width value

- src/Access/UserAccess.php
- tests/Unit/PermissionTest.php
```php
$user->hasAccess('access.key');
$user->addRole($role);
// clear cache permission data 
$user->clearCachePermission();
$user->hasAccess('access.key');
```
> Added a method to clear the permission check cache

- resources/views/fields/input.blade.php
- src/Screen/Fields/Input.php
- tests/Unit/Screen/Fields/InputTest.php
- Added `datalist` method for Input field
```php
Input::make('browser')
->title('Choose your browser from the list:')
->datalist([
'Opera', 'Edge', 'Firefox',
'Chrome', 'Safari',
]),
```
> Datalist for input

- stubs/app/Orchid/Screens/User/UserListScreen.php
Fixes the issue: when updating a user via oneAsyncModal all user roles were deleted.
> Fix wiping user roles when updating user via oneAsyncModal

- resources/views/fields/upload.blade.php
- src/Screen/Fields/Upload.php
- tests/Unit/Screen/Fields/UploadTest.php
Fixes #1532 
May be better to check filesystem storage properties for [url|visibility]
```
'url' => env('APP_URL').'/storage',
'visibility' => 'public',
```
Not sure if this is used for S3 so feel free to decline merge if this breaks anything and i'll take another look. Another solution posted in the issue.
> Hide file download link for non-public storage

- stubs/app/Orchid/Screens/User/UserEditScreen.php
UserEditScreen stub more reasonable for CREATE
- When creating a new user, `Remove` and `LoginAs` button is not available.
- When creating a new user, `Save` button is not available for blocks.
- Screen name `Edit User` for Editing, `Create User` for Creating.
> UserEditScreen stub more reasonable for CREATE

- src/Attachment/Models/Attachment.php
Fixes 
When creating a notification with an overridden platform User model, notifications failed to show. DB had Orchid\Platform\Models\User as type instead of mapped model. e.g
```php
$orchidUser = $event->attachment->user;
$user = \App\Models\User::find($orchidUser->id);
$user->notify(new \App\Notifications\Processed($event));
```
Can now be:
```php
$orchidUser = $event->attachment->user->notify(new \App\Notifications\Processed($event));
```
> Map related User model

- src/Platform/Commands/AdminCommand.php
- Make id option in `orchid:admin` command accept values [matching the behavior described in the docs](https://orchid.software/en/docs/access/#admin-creation) (Fixes #1571)
> Fix: id option in orchid:admin command accepts values (fixes #1571)

- resources/views/actions/menu.blade.php
- src/Screen/Actions/Menu.php
Fixes #
if name and slug are different the dropdown menu does not work
- use slug for dowpdown menu id
> Make submenu id equal to the slug

- resources/views/layouts/pagination.blade.php
> fix pagination repositility

- phpunit.xml
- src/Screen/Field.php
- tests/Unit/FieldTest.php
Fixes #
Assume we have a input with name `article[tags][text][]` the `old()` input name should be `article.tags.text` in the current state it returns an extra `.` to the name `article.tags.text.`
> Fix old name from request

- src/Screen/Fields/DateTimer.php
- tests/Unit/Screen/Fields/DateTimerTest.php
Additional methods implemented:
- available
- unavailable
- max
- min
- weekNumbers
- disableMobile
- inline
- shorthandCurrentMonth
- showMonths
- position
Checked the picker works manually in the browser, more tests would be good to add if time permits.
> Implemented additional flatpickr.js methods for DateTimer field.

- resources/views/layouts/table.blade.php
- tests/Unit/Screen/Layouts/TableTest.php
I am currently using Orchid and I am working on displaying the records of a **Query Builder** in a table.
I am using filters on that query and I paginate the results.
The problem happens that when I filter and no results are found.
Then the target goes to make an empty collection and the default message that there are no records is not displayed.
"There are no records in this view"
Example of my screen class - method query
```php
$orders = Order::query()
->filters()
->filtersApplySelection(MySelection::class)
->get();
return [
'orders' => $orders->isEmpty() ? $orders : $orders->toQuery()->orderBy('orders.created_at', 'desc')->paginate(10),
]
```
And I can't, I can't paginate an empty collection.
> [Hotfix] Support collection in target table

- resources/views/actions/menu.blade.php
There is an issue wherein when the Menu item has null name, icon, and badge, an empty space will still be rendered.
When you mouse hover on this empty space, the "hover animation" is still shown.
Here is an example menu that I want to do:
```
Menu::make()
->title('Settings')
->permission([
'platform.settings.general',
'platform.settings.mail',
]),
Menu::make('General')
->icon('settings')
->permission('platform.settings.general')
->route('platform.settings.general'),
Menu::make('Mail')
->icon('envelope')
->permission('platform.settings.mail')
->route('platform.settings.mail'),
```
In the code above, I only want to display the "title" without the fuss of animations / empty spaces so that I can "group" the Mail and General menus.
I think this would be useful if you want to group together …
> Fixed Menu showing empty space when name, badge, and icon is null

- src/Attachment/Engines/Generator.php
Fixed a possible issue where, while uploading files via the console, the time() function may return the same value, and at the same time you have two different files, but with the same name.
In this case, the Generator's method name() generates the same SHA-1 hash for two different files, overwriting existing file in the storage folder.
> Fix attachment generator file name SHA-1

- resources/js/controllers/listener_controller.js
When a field is part of trigger but it doesn't get rebuilt by listener, it will keep dispatching same event over and over due to the event listener callback being an anonymous method. With this change, the callback method is changed to be a known identified method so it gets dispatched to the same element only once and would prevent unlimited http requests being made for 1 field change.
This issue is replicable by creating a listener which listens on couple of fields but in the layout of the listener, that field which are listened to are not generated and they are generated through another layout in the page.
Fixes #
Listener field triggering the change event and make same http requests many times and keeps increasing.
The callback method of the event listener should be identified as a …
> Fixing listener to trigger event multiple times when the field is not included in the listener to be rebuilt

- src/Platform/Http/Controllers/RelationController.php
- tests/Feature/Platform/RelationsTest.php
Fixes #2006 
Search columns are grouped together correctly and separated from scope conditions
from
```sql
select * from `locations` where (`TG` = ? and `name` like ? or `code` like ?)
```
to
```sql
select * from `locations` where `TG` = ?  and (`name` like ? or `code` like ?)
```
> corrected searchColumns grouping

- resources/views/fields/upload.blade.php
Media search modal is always rendered in upload field even if media is disabled.
Don't render modal search media if media is not enabled.
> Don't render modal search media when disabled

- resources/views/layouts/filter.blade.php
- allows filters to grow if there is space
- makes all filters (selects and inputs) the same size
- adds a minimum width of 200px to prevent tiny inputs
- does not compromise mobile
> Better filter layout

- resources/js/controllers/listener_controller.js
Add a custom event triggered when listener has finished updating the elements
Fixes it is possible to run js after a lister has updated the elements, for example it's possible to rehydrate Livewire components with
```js
document.addEventListener("orchid:listener:post-render", () => {
Livewire.start();
});
```
> Add a custom event orchid:listener:post-render

- resources/views/fields/upload.blade.php
Renamed .sr-only and .sr-only-focusable to .visually-hidden and .visually-hidden-focusable
See https://getbootstrap.com/docs/5.1/migration/#helpers
> Screen reader classes are now visually-hidden

- resources/views/layouts/modal.blade.php
This notification will appear when you open the modal:
Please replace data-target="modal.title" with data-modal-target="title". The data-target attribute is deprecated and will be removed in a future version of Stimulus.
> data-target attribute is deprecated

- resources/js/controllers/upload_controller.js
Fixes `hasOwnProperty`
`hasOwnProperty` does not check for the specified property in the object's prototype chain.
> Fix hasOwnProperty dot path

- stubs/app/Orchid/Screens/User/UserListScreen.php
- stubs/app/Orchid/Screens/User/UserProfileScreen.php
Fixes #2163
- change the saveUser() method validation unique rule to find by email instead of slug
```PHP
$request->validate([
'user.email' => [
'required',
// Rule::unique(User::class, 'slug')->ignore($user),
Rule::unique(User::class, 'email')->ignore($user),
],
]);
```
- change `password` rule to `current_password` rule to match laravel 9  [new rule](https://laravel.com/docs/9.x/validation#rule-current-password)
- make guard selection dynamic depending on the config in the current_password rule
```PHP
$guard = config('platform.guard' , 'web');
$request->validate([
'old_password' => 'required|current_password:'.$guard,
'password'     => 'required|confirmed',
]);
```
> updatin "update password validation rule" and changing "unique validation" for users by Email

- src/Attachment/Engines/Generator.php
- src/Attachment/File.php
- tests/Unit/AttachmentTest.php
Fixes #2166
this is a clean version of this [pull request](https://github.com/orchidsoftware/platform/pull/2167)
add the ability to the user to choose a different path without extending the generator, benefits : 
- the path can be dynamic 
- you don't have to set only one generator
- backward compatible ( no existing method changes )
add `$path` param to and `Generator`  null as default value , null will keep it the default way Y/m/d
add `path(?string $path)` method to `File`
adding `public function testAttachmentCustomPath(): void` test
```PHP
return $this->path ?? date('Y/m/d', $this->time());
```
```PHP
public function path(?string $path = null) {
$this->engine->setPath($path);
return $this;
}
```
```PHP
$upload = $attachment->path($this->path)->load();
```
> Custom storage path feature

- resources/views/fields/upload.blade.php
Fixes #
Change data-upload-target="upload.description" into data-upload-target="description" to follow with commit #2228
> Fix upload description target

- stubs/app/Orchid/Screens/User/UserEditScreen.php
- Fixed filling in a password when creating a user
At the moment, when we try to create a user, we get error - "Field 'password' doesn't have a default value (SQL: insert into `users`..."
so the password is not filled in here
https://github.com/orchidsoftware/platform/blob/16ea2e13ffab14157fdbd0ab1c679146901073bf/stubs/app/Orchid/Screens/User/UserEditScreen.php#L188
or here 
https://github.com/orchidsoftware/platform/blob/16ea2e13ffab14157fdbd0ab1c679146901073bf/stubs/app/Orchid/Screens/User/UserEditScreen.php#L183-L185
> Fixed filling in a password when creating a user

- src/Platform/Dashboard.php
- tests/Unit/PermissionTest.php
- Currentily if you want to render permissions or create users programattically is all or nothing. This has the intension to return permissions by groups so assign and show permissions is more flexibble according the context.
> Add group filter to get permissions

- resources/views/layouts/base.blade.php
While it is more than a command and the command buttons have a background, space will be created between them.
> add space between commands

- resources/views/fields/relation.blade.php
- resources/views/fields/select.blade.php
- src/Screen/Fields/Relation.php
- src/Screen/Fields/Select.php
- src/Screen/Fields/TimeZone.php
- tests/Unit/Screen/Fields/RelationTest.php
- tests/Unit/Screen/Fields/SelectTest.php
Fixes [#2217](https://github.com/orchidsoftware/platform/issues/2217)
- Added `nullable()` method for `Select` and `Relation` fields allowed to save nullable value if no value selected
I have `Project` model. Every Project may have `Branch`. But it is nullable column
```php
// migration
$table->foreignId('branch_id')
->nullable()
->constrained()
->onDelete('set null');
// relation
public function branch()
{
return $this->belongsTo(Branch::class)->withDefault([
'name' => 'Иное',
]);
}
// screen
Relation::make('project.branch_id')
->fromModel(Branch::class, 'name')
->chunk(50)
->title('Отрасль'),
```
Currently I cannot set null to a `branch_id` if value was set before (if I clear select, hit "Update" button, it is will not affect database value as request does not contain `branch_id` key) …
> Allow to set NULL value for `Select` and `Relation` fields when cleared

- config/platform.php
When using Laravel Sail with PHP 8.1 I've noticed my `laravel.log` has a lot of warnings. Even on fresh Laravel-Orchid installation. Happens only with PHP 8.1
It repeated this lines again and again
```
laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at /var/www/html/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:207)
laravel.WARNING: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 75  
```
So when I start digging, I found it comes from config `platform.php` file
```php
'template' => [
'header' => null,
'footer' => null,
],
```
and within …
> Change default `platform.php` file to prevent log warnings with PHP 8.1

- resources/views/actions/menu.blade.php
- src/Screen/Actions/Menu.php
Fixes #
- Added a parent attribute & a setter for the same attribute in the Menu class to store the parent of the sub menu.
- Added a isset check for $parent in the menu.blade file and instead of setting "data-bs-target" to "headerMenuCollapse" as default, set it to $parent if it is not null.
> Fix for Nested sub menus in the Sidebar.

- stubs/app/Orchid/Screens/User/UserEditScreen.php
The string 'You can revert to your original state by logging out.' in the UserEditScreen stub isn't localized yet. This pull request modifies the hard coded string to a localized one.
> add localization for the notice displayed before impersonating a user

- src/Platform/Http/Middleware/Access.php
- src/Screen/Screen.php
Developer can change default 403 error response by overriding `Screen::unaccessed` method.
Some project may need to hide screens from admins with lower access lever or hide the very existance of admin panel. That can be achieved by making `unaccessed` return 404 code.
`unaccessed` may also return \Illuminate\Http\Response instance so that user can be redirected to route, any view can be shown etc.
> Added unaccessed method to Screen

- resources/views/auth/lockme.blade.php
- resources/views/auth/signin.blade.php
- src/Screen/Fields/Input.php
This PR aims to allow the use of the inline `inputmode` attribute which enables the keyboard to type to be changed on mobile devices.
More details can be found here:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
- https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/
- https://www.twilio.com/blog/html-attributes-two-factor-authentication-autocomplete
Example usage:
```php
use Orchid\Screen\Fields\Input;
Input::make('token')
->type('text')
->inputmode('numeric')
->pattern("[0-9]*")
```
> Added attribute `inputmode` for input tag

- tests/Browser/ModalTest.php
- Fixes the field validation error message expected in methods `testReopenModalForValidationFailed` and `testDoubleReopenModalForValidationFailed`.
Now message "The message must be at least 10 characters." is expected, but in reality the [template ](https://github.com/illuminate/translation/blob/d6f7bf61b3d223abf0c279ea0d8d127e8f51c095/lang/en/validation.php#L103)is "The :attribute **field** must be at least :min characters.", that is "field" is missing.
Therefore, we are waiting for text that will never appear.
> Fixed `ModalTest` expected validation error message

- src/Screen/Field.php
При формировании ссылки:
```
TD::make('title', 'Заголовок')
->filter(TD::FILTER_TEXT)
->render(static function(Article $article) {
return Link::make($article->title)
->route('article.platform.edit', $article);
}),
```
получилось так, что название статьи было задано (на скорую руку случайно), как catalog, и так случилось, что лежал файл локализации catalog.php в итоге при срабатывании кода на приведённой строке кода вернулся массив. предлагаю добавить доп. проверку, что функция перевода вернула строку и только тогда подменять name у поля Link
```
collect($this->attributes)
->intersectByKeys(array_flip($this->translations))
->each(function ($value, $key) use ($lang) {
$translation = __($value, [], $lang);
$this->set($key, is_string($translation) ? $translation : $value);
});
```
> Array to string conversion

- tests/Unit/Screen/Layouts/ChartTest.php
- Fixes check whether the export button is enabled.
The last commit https://github.com/orchidsoftware/platform/commit/936632a63bec04c4c70df34c63311f3914a39d57#diff-d541a53fe6317d98b6936370f6b096f9a28b6859b8af68f9304019a073f06947L93-R93 changed the default state, so the test `testEnabledExportButton` failed.
> Fixed `ChartTest` export button

- src/Platform/Providers/ConsoleServiceProvider.php
- src/Platform/Providers/FoundationServiceProvider.php
Solves https://github.com/orchidsoftware/platform/issues/2586
Registers all console-based commands, migrations, publishers and other things in ConsoleServiceProvider, loaded only when running in console, to avoid doing these for HTTP requests.
Allows HTTP requests to execute a little faster, especially under load/concurrency.
> Load all console-based registrations in console only

- src/Screen/Screen.php
If a public static property is used in Screen class, the system tries to assign a value to it, which causes exception "Accessing static property $xxx as non static"
> Filter static properties in Screen

- src/Platform/Providers/FoundationServiceProvider.php
Moves calling `registerTranslations` method from `boot` method to `register` method
Set locale
```php
// config/app.php
'locale' => 'ru'
```
Before changes:
```
Illuminate\Translation\Translator {#275 ▼ // public/index.php:55
#parsed: array:13 [▶]
#loader: Illuminate\Translation\FileLoader {#274 ▶}
#locale: "ru"
#fallback: "ru"
#loaded: array:1 [▼
"*" => array:14 [▼
"*" => array:1 [▶]
"System" => array:1 [▶]
"Roles" => array:1 [▶]
"Users" => array:1 [▶]
"Main" => array:1 [▶]
"Attachment" => array:1 [▶]
"Sign in to your account" => array:1 [▶]
"Email address" => array:1 [▶]
"Enter your email" => array:1 [▶]
"Password" => array:1 [▶]
"Enter your password" => array:1 [▶]
"Remember Me" => array:1 [▶]
"Login" => array:1 [▶]
"The application code is published under the MIT license" => array:1 …
```
> Updates translation registration

- resources/views/auth.blade.php
> Fix top margin in auth.blade.php

- composer.json
- resources/views/layouts/filter.blade.php
- resources/views/layouts/selection.blade.php
- src/Filters/Filter.php
- src/Screen/Layouts/Selection.php
- tests/App/Filters/PatternFilter.php
- tests/Unit/FiltersTest.php
This PR aims to enhance the functionality and usability of filters in the project. The changes made in this PR address multiple areas simultaneously, resulting in an improved experience for users.
One of the primary enhancements included in this PR is the introduction of pattern string support in parameter instructions. With this update, developers can now define parameter patterns using a convenient syntax. The following code snippet demonstrates its usage:
```php
/**
* The array of matched parameters.
*
* @var null|array
*/
public $parameters = [
'pattern.*',
];
```
This change simplifies parameter declaration and improves clarity when working with filters.
Additionally, this PR eliminates the need to explicitly set the `$display` attribute for filters. Previously, developers had to …
> Improving Filter Experience

- resources/views/layouts/accordion.blade.php
- src/Screen/Layouts/Accordion.php
- Add option to make accordion items stay open when another item is opened.
```
Layout::accordion([
'Personal Information' => [
Layout::rows([
Input::make('user.name')
->type('text')
->required()
->title('Name')
->placeholder('Name'),
Input::make('user.email')
->type('email')
->required()
->title('Email')
->placeholder('Email'),
]),
],
'Billing Address'      => [
Layout::rows([
Input::make('address')
->type('text')
->required(),
]),
],
])->stayOpen()
```
> Make accordion items stay open when another item is opened.

- resources/views/components/popover.blade.php
- tests/Unit/Support/BladeComponentTest.php
- Fixed missing `bs` in popover data attributes.
- Added test.
In addition, I will explain why `trigger` was changed to `click`.
In the current state, the value from the data attribute is not used and the behavior is exactly like `click`, that is, it opens on the first click, and closes on the second click.
If use `focus`, then something strange turns out in general - it opens on the first click, and you can close it only if you click the second time and additionally again in another place, although in theory it should close on the second click in another place.
@tabuna Do you have a problem with trigger `focus` and how should I proceed?
> Fixed missing `bs` in popover data attributes

- resources/sass/core/modals.scss
- fix: modal placeholder not hiding on small screen
Most likely just by accident these rules were added not for all screen sizes, but only for more than 768px.
> Fixed hiding modal placeholder on screen size < 768px

- resources/views/layouts/base.blade.php
Fixes #2763
Calling `@section` with a null value trigger a bug that does not close an output buffer, causing PHPUnit to mark tests that use this view without name or description defined to be marked as risky.
Changes introduced by d9700e9753ba09c20e3e4e0b22305960f8801d04 removed the `e` function call that fallback to empty string when called with null.
Using a `string` cast force `null` values to be empty string.
More references: https://laracasts.com/discuss/channels/testing/test-code-or-tested-code-did-not-only-close-its-own-output-buffers-actingas
> Enforce non null @section values to prevent dangling output buffers

- resources/views/fields/select.blade.php
- tests/Unit/Screen/Fields/SelectTest.php
> Fixed: If 'select' key is indecies, lost 'selected' attribute. Added unit test

- src/Screen/Fields/Select.php
- tests/App/Enums/RoleNames.php
- tests/Unit/Screen/Fields/SelectTest.php
This PR gives option to change displayed values for Select Field based on Enum
```php
// Enum
enum RoleNames: string
{
case Admin = 'admin';
case User = 'user';
public function label(): string
{
return match ($this) {
self::Admin => 'Administrator',
self::User => 'Regular user',
};
}
}
// Layout
Select::make('fromEnum')
->fromEnum(RoleNames::class, 'label'), // pass second option as method name
```
This will generate values based on label method
> feat: add option to customize display name for select based on enums

- resources/views/app.blade.php
- Fix form login align center on /admin/login page with screen width from 1200px to 1399px
> Fix row in container-fluid to center on login

- src/Screen/Layouts/Metric.php
This PR fixes error when using metrics and modals are presents at the same time (not within modal)
I will not open issue, basically steps to reproduce
1. Install Orchid, go to users list, click on "edit email" modal - everything is OK
2. Add dummy metric layout
```php
public function query(): iterable
{
return [
// ...
'metrics' => 1,
];
}
public function layout(): iterable
{
// ...
Layout::metrics(['Metrics' => 'metrics']),
}
``` 
3. Click same button again - modal data was not loaded (we can see skeleton and 500 error in a console)
Default data for metrics currently is empty array so it is passes `is_array()` check within `layouts/metric.blade.php` (currently [line 13](https://github.com/orchidsoftware/platform/blob/master/resources/views/layouts/metric.blade.php#L13)) and expects …
> Fix: change default value for metrics layout to be compatible with modals

- src/Platform/Providers/EventServiceProvider.php
Fixes #2828
Laravel 11 automatically disable events auto discovery if a different instance of EventServiceProvider is loaded. This is handle by `shouldDiscoverEvents` method at line [137 in Illuminate/Foundation/Support/Providers/EventServiceProvider.php](https://github.com/laravel/framework/blob/v11.6.0/src/Illuminate/Foundation/Support/Providers/EventServiceProvider.php#L137).
Since Orchid extend and register it's own version of `EventServiceProvider` the class check at `get_class($this) === __CLASS__` starts to fail since it's executed with an instance of Orchid `EventsServiceProvider`.
I propose to override the `shouldDiscoverEvents` in order to match `get_class` and `__CLASS__` values and re-enable the auto discovery.
> Allow events AutoDiscovery in Laravel 11

- resources/views/app.blade.php
- resources/views/layouts/base.blade.php
- src/Screen/Screen.php
Added the ability to assign a stimulus controller to the screen.
Usage:
```
class PlatformScreen extends Screen
{
...
public function frontendController(): string
{
return 'hello';
}
...
}
```
> Add frontend controller in screen.

- resources/views/layouts/modal.blade.php
- src/Screen/Layouts/Modal.php
**Feature:** Added support for modal with XL (Extra large) size.
- Updated modal component to handle XL size configurations.
- Ensured consistent styling and behavior for the new size option.
**Bug Fix:** Corrected the misplaced `$type` variable.
- Moved `$type` to the appropriate location in the layout template.
- Verified that the fix does not impact other functionalities or cause regressions.
> Add support for modal with XL size and fix $type position

- resources/js/controllers/datetime_controller.js
- resources/js/controllers/select_controller.js
- src/Screen/Fields/DateTimer.php
The "maximumSelectionLength" option in select_controller.js was not working. The problem was solved by adding parentheses.
Before the relevant change is made;
In order to use the formatting feature correctly, the "altInput" and "altFormat" attributes recommended by the "flatpickr" package have been added.
> Update select_controller.js & datetime_controller.js

- src/Screen/Field.php
- src/Screen/Screen.php
This PR introduces a significant change to how screen state is handled. To better understand this, let’s first review the current behavior:
All recorded public properties of the screen are wrapped in a signalizer, which typically increases the length of the data since its contents are serialized:
```php
// Serialized:
O:7:"Example":2:{s:9:"property1";s:6:"value1";s:9:"property2";s:6:"value2";}
```
The data is then encrypted, further increasing the text length:
```php
// Encripted:
Tzo3OiJFeGFtcGxlIjoxOntzOjk6InByb3BlcnR5MSI7czo2OiJ2YWx1MSI7czo5OiJwcm9wZXJ0eTIiO3M6Njoi dmFsdWUiO30=
```
As a result, if a user writes too much data into a public property, such as a model with many relationships, this impacts the length of the response/request. In extreme cases, this can lead to a 413 – …
> Reduce Data Transfer for State Restore

- src/Screen/Field.php
Hello!
I noticed the Field class does not have a way to use [accessibility attributes](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA). The proposal adds "aria-*" to the universal attributes array.
- Added the possibility to set accessibility attributes for fields
> Add "aria-*" to $universalAttributes in Field.php

- src/Screen/Concerns/ModelStateRetrievable.php
- src/Screen/Screen.php
- tests/App/Screens/SerializeRetrievableScreen.php
- tests/App/Screens/SerializeScreen.php
- tests/Unit/Screen/ScreenSerializeTest.php
When we pass arguments to the constructor for dependency injection, we expect these arguments to be properly initialized and available for use with the object's methods after deserialization.
```php
public function __construct(
private readonly NewsService $newsService,
private readonly CatalogService $catalogService,
private readonly ConstructorService $constructorService
) {
// ...
}
```
However, in the current implementation, this can lead to errors such as:
```php
Serialization of 'Closure' is not allowed
```
This change aims to ensure the reinitialization of the class with all its arguments after deserialization, similar to how it is handled for GET requests. This will help avoid serialization issues and correctly restore the object's state.
> Fixed screen constructor property initialization during deserialization

- src/Screen/Screen.php
Fixes #2879
- Iterate over parent classes public properties while creating public properties list;
- Stop at base Screen class to avoid changes to Orchid native properties;
> Retrieve Screen inherited public properties from parent classes

- src/Screen/Components/Cells/DateTimeSplit.php
Fixes #
- Fixing 12-hour format to 24-hour format of an hour with leading zeros on `DateTimeSplit` component
> Fixing 12-hour format to 24-hour format of an hour with leading zeros

- src/Screen/Field.php
Issue
When the return type of the value method is self, PHPStan gives this error:
for this code snippet that inherit your **value** method.
```
public function value($value): static
{
if (empty($value)) {
$value = [];
}
return parent::value($value);
}
```
PHPStan works correctly only when you change the return type from **self** to **static**, as I suggested in my PR. So, you need to change to **static** if you want the method to be compatible with subclasses.
> PHPStan issue when the return type of Field::value is self

- src/Screen/Field.php
- tests/Unit/FieldTest.php
This PR introduces a new `addClass()` method to the `Field` class. This method allows adding new classes to the existing ones without overwriting them.
- Added `addClass()` method to `Field` class
- Updated class documentation
- Added unit tests for the new method
- Updated CHANGELOG.md
```php
$field->addClass('new-class');
$field->addClass(['class1', 'class2']);
> Add addClass() method to Field class for easier class manipulation

- stubs/app/Orchid/Layouts/User/UserPasswordLayout.php
Fixes #
Without calling the method, the user may not always notice that it is necessary to add a password when creating a new user in the platform. This leads to a 500 error "Field 'password' doesn't have a default value"
> Updated UserPasswordLayout.php

- src/Screen/AsSource.php
When calling the `getContent()` method, the model is transformed into a flat structure, allowing for dot notation searches.
However, converting the model to an array triggers all its type casts.
In my experience, direct access to specific attributes is far more common than dot notation usage. Therefore, in this Pull Request, I adjusted the value retrieval order so that type casting only occurs when dot notation is needed.
In my experiments, this change resulted in a noticeable performance improvement.
> Fast Attribute Access

- pint.json
- src/Platform/Http/Controllers/RelationController.php
This updates search functionality to use the `whereLike` method, introduced in Laravel v11.17.0, for performing case-insensitive searches. For Laravel versions below 11.17.0, the existing implementation using `like` is retained.  
The `whereLike` method adapts to the specifics of different databases:  
- **PostgreSQL**: Uses `ilike` for case-insensitive search.  
- **MySQL**: Uses `like`.  
- **SQLite**: Uses `like`.  
- **SQL Server**: Behavior depends on the column/database collation.
> Use `whereLike` for case-insensitive search

- resources/views/fields/attach.blade.php
The values specified for the `Attach` field (`Attach::make(...)->errorTypeMessage('...')->errorMaxSizeMessage('...')`) are not being passed correctly.  
I haven't tested the functionality of `errorMaxSizeMessage` yet, nor have I verified other aspects. However, it seems that nothing is broken, and everything else works as expected. :)
> Error Notifications Are Not Passing Correctly in Attach

- resources/views/layouts/accordion.blade.php
- src/Screen/Layouts/Accordion.php
Fixes #
- Added open method to Accordion.php. Allows you to specify which accordions should be open when the page is opened. Accepts a string and an array, if the method is not called, the first accordion will be opened by default, as it was before adding the method
> Added activeAccordion method to Accordion.php

- resources/sass/core/layout.scss
- resources/views/layouts/accordion.blade.php
Fixes #2941
- Replaced `<h6>` with `<button>` to make the Accordion component more semantic and improve accessibility for screen readers.
- Added a `:focus-visible` outline style to `a`, `button`, and `.btn` elements to enhance focus visibility, specifically for keyboard users.
> Improve Accordion accessibility

- .github/workflows/quality.yml
- composer.json
This PR addresses issue #2951, where updating to `orchid/platform` v14.45.0 caused an unexpected downgrade of `laravel/framework` and other dependencies.  
- Fixed Laravel version conflict in `composer.json` to ensure compatibility.  
- Added a check for outdated dependencies to prevent similar issues in the future.
> Fix Laravel Version Conflict

- src/Platform/Notifications/DashboardMessage.php
- tests/Feature/Platform/NotificationTest.php
Sometimes I don't want to create a full event using the `artisan make:notification` command just for small messages in the admin panel. It would be great to have the option to send notifications like this:
```php
$user->notify(DashboardMessage::make()
->title('Simple Notification')
->action('#')
->message('Lorem ipsum dolor sit amet, consectetur adipiscing elit.')
->type(Color::INFO)
);
```
> Added Simple Persistent Notification Sending

- src/Alert/Toast.php
- tests/Unit/AlertTest.php
This PR introduces two new methods to improve the `Toast` notification system:  
- `persistent(bool $persistent = true)`: Prevents the toast from auto-hiding, keeping it visible until dismissed manually.  
- `seconds(int $seconds)`: Allows setting the toast delay in seconds instead of milliseconds for better readability.  
These additions provide more flexibility in managing toast notifications, making it easier to configure their behavior without manually handling milliseconds or overriding auto-hide settings.  
- Added the `persistent` method to toggle auto-hide behavior.  
- Added the `seconds` method to simplify delay configuration.  
- Added/updated test cases to ensure proper functionality.  
Run the test suite to verify that toast notifications behave as expected with the new …
> Add persistent and seconds methods to Toast notification

- src/Screen/Actions/Button.php
Fixes #
- Pass the text for translation to the "confirm" method of the "Button" class
Before:
```php
Button::make('Title')
->icon('bs.trash3')
->confirm(__('Conformation'))
->method('destroy')
->canSee($this->model->exists),
```
After:
```php
Button::make('Title')
->icon('bs.trash3')
->confirm('Conformation')
->method('destroy')
->canSee($this->model->exists),
```
> Fix: Added the "confirm" attribute to the property translations

- src/Platform/Commands/ChartCommand.php
- src/Platform/Commands/FilterCommand.php
- src/Platform/Commands/GeneratorCommand.php
- src/Platform/Commands/ListenerCommand.php
- src/Platform/Commands/PresenterCommand.php
- src/Platform/Commands/RowsCommand.php
- src/Platform/Commands/ScreenCommand.php
- src/Platform/Commands/SelectionCommand.php
- src/Platform/Commands/StubPublishCommand.php
- src/Platform/Commands/StubsCommand.php
- src/Platform/Commands/TabMenuCommand.php
- src/Platform/Commands/TableCommand.php
- src/Platform/Providers/ConsoleServiceProvider.php
Fixes #
- Added command : php artisan orchid:stub-publish
After:
After executing the publishes in the structure, the modified stubs are picked up during generation.
```shell
stubs
└── orchid
└── platform
├── chart.stub
├── filters.stub
├── listener.stub
├── presenter.stub
├── rows.stub
├── screen.stub
├── selection.stub
├── table.stub
└── tabMenu.stub
```
> Feature: Publish stubs

- src/Screen/Fields/RadioButtons.php
`@method` annotations had an invalid "`statics`" return types which causes PHPStan to complain. I replaced them with `$this`, as it is also used in other Field classes.
> RadioButtons: fix method annotation return type

- tests/Console/ArtisanTest.php
- tests/Feature/Platform/RelationsTest.php
- tests/Unit/AlertTest.php
- tests/Unit/FieldTest.php
PHPUnit 12 drops support for docblock-based @dataProvider annotations.
This change uses PHP 8.1+ attributes to define data providers,
ensuring forward compatibility.
> Avoid PHPUnit 12 conflict by using `Attributes\DataProvider`

- src/Screen/Actions/Button.php
- tests/Unit/Screen/Actions/ButtonTest.php
When passing Eloquent models to the `method()` or `parameters()` call, 
the system now automatically extracts the model key using `getKey()`. 
This allows writing cleaner code like:
```php
->parameters(['user' => $user])
```
instead of:
```php
->parameters(['user' => $user->id])
```
Includes a test case to verify that Eloquent models are properly resolved to their primary key in form action URLs.
> Support passing Eloquent models as action parameters

- src/Screen/Field.php
- src/Screen/Fields/Input.php
- tests/Unit/Screen/Fields/InputTest.php
Implemented functionality to render HTML content in both `help()` and `title()` methods of the Input field.
This method accepts a plain text string, or an instance of `Illuminate\Support\HtmlString` or `Illuminate\Contracts\Support\Htmlable`. This allows you to render HTML, or even markdown, in the helper text:
```php
use Illuminate\Support\HtmlString;
use Illuminate\Support\Str;
Input::make('name')
->help(new HtmlString('Your <strong>full name</strong> here, including any middle names.'))
Input::make('name')
->title(Str::of('Your **full name** here, including any middle names.')->inlineMarkdown()->toHtmlString())
```
> Added support HTML rendering in help and title fields

- src/Screen/Field.php
- src/Screen/Layout.php
- src/Screen/Layouts/Listener.php
This PR improves performance of UI component hashing by replacing the legacy `sha1` algorithm with the much faster and more modern `xxh3` hash.
Benchmarks show `xxh3` is up to 10x faster than `sha1` for short strings and small payloads, making it a better fit for UI-level hashing.
https://php.watch/versions/8.1/xxHash
> Refactor component hashing: switch to `xxh3`

- src/Screen/Concerns/ModelStateRetrievable.php
- tests/Unit/Screen/ScreenSerializeTest.php
- Updated `ModelStateRetrievable` trait to handle unsaved models correctly.
- Added test to validate serialization/deserialization behavior for unsaved models.
> Fix serialization and deserialization for unsaved Eloquent models

- src/Attachment/Engines/Generator.php
This PR introduces a dedicated `hashAlgorithm()` method to centralize the hash algorithm used for:
- Generating file names
- Generating file content hashes
> Extract hash algorithm to protected method for easier override

- resources/js/controllers/attach_controller.js
File sorting does not work on certain server types because they expect the `Content-Type: application/json` header from the client.
> Fix file sorting issue on servers expecting `Content-Type`

- config/platform.php
Changes the default value of 'refresh-scroll' in the Turbo config to 'preserve',so that scroll position is retained after Turbo-driven page refreshes.
Improves user experience when usage https://github.com/orchidsoftware/platform/pull/2997 or alternatives.
> Changed set Turbo scroll behavior to `preserve` by default
