- docs/en/documentation.md
Fixes #
- fixed typo from "Installation" to "Contributor Guidelines"
> Fixed typo in the table of content

- resources/views/container/systems/category/info.blade.php
> fix calling relation for new object in template

- docs/ru/field.md
Ссылка на параметры маски.
Мне пришлось искать, когда разбирался)
> add comment to docs: Field -> Mask

- src/Platform/Core/Models/Post.php
- src/Platform/Core/Traits/MultiLanguage.php
- src/Platform/Core/Traits/RepositoryFields.php
revert \Orchid\Platform\Core\Traits\MultiLanguage
added \Orchid\Platform\Core\Traits\RepositoryFields
> fix orchidsoftware/platform#426

- resources/views/fields/simplemde.blade.php
Поменял input на textarea так как не сохранял перенос строк и в документации рекомендовано использовать textarea.
> Change input on textarea

- docs/ru/field.md
- docs/ru/tutorial_blog.md
- docs/ru/widget.md
Change in docs
1. Wysiwyg theme
2. Added transfer of data to widgets
3. В туториал по блогу добавил пример переменной в виджет (на усмотрение).
> Change in docs

- resources/views/container/systems/roles/info.blade.php
- src/Platform/Http/Controllers/Systems/RoleController.php
Fixes #
Изучаю ваш труд, наткнулся на некоторую недоработку решил поправить.
> В разделе роли, если не пройдена валидация, значение остаются в полях

- docs/ru/screens.md
Users должен лежать в папке Screens, после создание в консоли.
Соответственно будет вводить заблуждение тех кто будет пытаться создать экран.
> Поправил в документации

- docs/ph/active.md
Fixes #
-Filipino Translation
-
-
> Tagalog Translation for active.md

- docs/ph/alert.md
> Tagalog Translation for alert.md

- docs/ph/authorization.md
> Tagalog Translation for authorization.md

- docs/ph/comments.md
> Tagalog Translation for comments.md

- docs/ph/behaviors.md
> Tagalog Translation for behaviors.md

- docs/ph/contributors.md
> Tagalog Translation for contributors.md

- docs/ph/form.md
> Tagalog Translation for form.md

- docs/ph/fields.md
> Tagalog Translation for fields.md

- docs/ph/documentation.md
> Tagalog Translation for documentation.md

- config/platform.php
- resources/views/fields/upload.blade.php
- routes/dashboard/systems.php
- src/Platform/Core/Models/Attachment.php
- src/Platform/Fields/Types/UploadField.php
- src/Platform/Http/Controllers/Systems/AttachmentController.php
У меня так работает:
```
'files'	=> Field::tag('upload')
->name('field.options.upload')
->title('Upload'),	
```
> Upload field

- resources/views/fields/list.blade.php
При редактировании созданного документа все элементы с одинаковым ключом [0] и уже записывается только последний.
> Bug fix list.blade.php

- resources/views/fields/list.blade.php
- src/Platform/Fields/Types/ListField.php
Точно косячный этот list. В post норм работал, добавил в экран - несохраняет.
Вроде сейчас и там и там должен работать.
Добавление индекса убрал, так как он итак по порядку сохраняет.
> List fix bug 2

- resources/views/container/layouts/modals.blade.php
А то, только одно модальное окно работало.
Когда больше одного, то работало только последнее.
> Fix modals.blade.php

- docs/ptpt/acess.md
Hello, I translated this file into Portuguese from Portugal.
Please let me know if what I've done is alright. Greetings!
Fixes #
-
-
-
> Translation to portuguese file acess.md

- docs/ptpt/configuration.md
> Translation to portuguese file: configuration.md

- docs/ptpt/comments.md
> Translation to portuguese file: comments.md

- docs/ptpt/behaviors.md
> Translation to portuguese file: behaviors.md

- docs/ptpt/authentication.md
> Translation to portuguese file: authentication.md

- docs/ptpt/alert.md
I translated this file into Portuguese from Portugal.
Greetings!
> Translation to portuguese file: alert.md

- docs/ptpt/active.md
Hi, I translated this file into Portuguese from Portugal.
Greetings!
> Translation to portuguese file: active.md

- docs/ptpt/form.md
> Translation to portuguese file: form.md

- docs/ptpt/filters.md
> Translation to portuguese file: filters.md

- docs/ptpt/field.md
> Translation to portuguese file: field.md

- docs/ptpt/extension.md
> Portuguese Translation for extension.md

- docs/ptpt/documentation.md
> Portuguese Translation for documentation.md

- docs/es/access.md
- docs/es/active.md
- docs/es/alert.md
- docs/es/athentication.md
- docs/es/behaviors.md
I translated the files: `access.md`, `active.md`, `alert.md`, `athentication.md`, and `behaviors.md`.
- 1054 translatable words have been translated to spanish (excluding links, paths, codes, and words that are suposed to remain unstranslated).
- I will continue to translate the whole docs folder. Every time I get to 1000 words I'll make a PR, Hope this is ok. Thank you!
> Docs folder - 5 files translated to Spanish

- docs/en/settings.md
- docs/ph/settings.md
- docs/ru/settings.md
> Change doc setting

- database/migrations/2018_04_08_153141_create_attachment_group_column.php
- public/js/tinymce/package.json
- resources/assets/js/controllers/upload_controller.js
- resources/views/fields/upload.blade.php
- src/Platform/Core/Traits/Attachment.php
- src/Platform/Fields/Types/UploadField.php
Fixes #
- migrate upload field from vue to stymlus
- fix upload field
- add group to attachmenttable
> Userscreen

- docs/en/tutorial_blog.md
> Fix blog documentation

- resources/views/fields/datetime.blade.php
- правка инициализации поля с flatpickr
> datetime.blade.php

- docs/en/installation.md
> Typo error in installation guide fixed. word "Come" changed to "Some"

- resources/sass/core/reset.scss
- resources/sass/core/tables.scss
- resources/sass/core/utilities.scss
- resources/sass/plugins/plugin.scss
- resources/views/container/layouts/link.blade.php
- resources/views/container/layouts/table.blade.php
- resources/views/partials/mainMenu.blade.php
> Menu and another style fix

- resources/views/fields/datetime.blade.php
- src/Screen/Fields/DateTimerField.php
- src/Screen/Screen.php
Думаю данный вариант доступа лучше.
Например если есть менеджер и администратор можно им дать доступ к экрану, а уже в самом  экране показывать кому что.
> Screen permission

- install-stubs/Orchid/Composers/MainMenuComposer.php
> Example menu

- install-stubs/Orchid/Entities/Post.php
- install-stubs/Orchid/Screens/Category/CategoryEditScreen.php
- src/Press/Models/Category.php
Add select categories to post.
> Select categories

- src/Platform/Models/User.php
> collection by default not set keys, mixed items unpredictable. Fixed.

- resources/js/controllers/fields/map_controller.js
Fixes #
- Autoscroll map
- Update coords on dragend
> Adding MapField autoscroll

- resources/views/container/layouts/selection.blade.php
> Removed unnecessary foreach in selection.blade.php

- install-stubs/Orchid/Layouts/User/UserFiltersLayout.php
- install-stubs/Orchid/Layouts/User/UserListLayout.php
- install-stubs/Orchid/Screens/User/UserListScreen.php
> User filter

- resources/views/container/posts/locale.blade.php
Fixes #
- добавил value в чекбокс locale
> add value='true' into post locale field

- src/Platform/Http/Controllers/Systems/ResourceController.php
Fix the issue with the resources when resource path has the same name with another extension.
> Issue with the resource paths

- .eslintrc.json
- resources/js/controllers/layouts/form_controller.js
Суть в чем. 
До этого вызывался метод контроллера, и в него передавался эвент, таргет которого являлся <a/>. 
Все проще. Берем форму и сабмитим ее. В метод контроллера прилетит эвент с формы. И все гуд. 
Также немного пофиксил контролер на ошибки eslint ( + добавил globals в конфиг)
> close #846 fix links in safari browser. change eslint rules

- resources/views/fields/button.blade.php
- src/Screen/Fields/Button.php
I think we need loadModalAsync for the button because sometimes you need to send data to the modal but if we using async modal it overriding attributes which should be sent with the params.
> Added support of async modal for the button field

- install-stubs/Orchid/Screens/Role/RoleEditScreen.php
- install-stubs/Orchid/Screens/Role/RoleListScreen.php
- install-stubs/Orchid/Screens/User/UserEditScreen.php
- install-stubs/Orchid/Screens/User/UserListScreen.php
Фикс проблемы описанной в issue
> ref #884 [Stubs] add needed permissions to roles and users screens

- src/Platform/Http/Controllers/Systems/RelationController.php
- src/Screen/Fields/Relation.php
- src/Support/Assert.php
1. Устранил ошибку в Relation, а то он у меня сохранял но не загружал (может из-за особенностей БД)
2. Добавил возможность загружать из любого класса как раньше. В applyScope пишем из какого метода запрос.
Можно проверить по AjaxWidget из старой документации [ссылка](https://github.com/orchidsoftware/orchid.software/blob/78f333bb9448ce382f6cc77da5a1a7da610f3dd2/source/ru/docs/field.md#отношения)
конструкция поля такая
```
Relation::make('data')
->title('My title')
->fromClass(AjaxWidget::class, 'text','id')
->applyScope('handler'),
```
> Update Relation Field

- src/Platform/Http/Controllers/Systems/RelationController.php
Fix issue with the fromClass nullable search string. Added support of the nullable search. Additional check for the search string.
> Relation field fix for the null search string

- src/Screen/Fields/Select.php
array_merge change value of indexes in empty methode
> fix: problem in index

- install-stubs/Orchid/Layouts/User/UserListLayout.php
- Fixed a typo that prevents from modifying user
> Fixed a typo

- resources/views/app.blade.php
- src/Platform/Commands/AssetsCommand.php
- src/Platform/OrchidPreset.php
- src/Platform/Providers/FoundationServiceProvider.php
- webpack.mix.js
[#915](https://github.com/orchidsoftware/platform/issues/915)
> Adds ability to publish Orchid's asset files

- resources/views/app.blade.php
- src/Platform/Presets/Orchid.php
- src/Platform/Presets/orchid-stubs/dashboard.js
- src/Platform/Presets/orchid-stubs/hello_controller.js
- src/Platform/Presets/orchid-stubs/webpack.mix.js
- src/Platform/Providers/FoundationServiceProvider.php
- tests/Console/ArtisanTest.php
> Adds stimulusjs preset (artisan preset orchid)

- resources/lang/ru.json
- resources/lang/uk.json
- resources/views/layouts/selection.blade.php
- src/Screen/Fields/Relation.php
As my fluent english colleague said it spell like you are going to the gym to improve your condition :)
> Rename "Add condition" to "Filters"

- package.json
Пакет cross-env был установлен, но команда для запуска не была прописана.
Из-за чего в Windows скрипты не запускались.
> Fixed running scripts in package.json

- resources/views/actions/modal.blade.php
Fixes ModalToggle class being overrided
> Fix ModalToggle class override

- resources/views/layouts/table.blade.php
Make table responsive
Fixes mobile compatibility
- Support mobile compatibility
- Inside docs: https://getbootstrap.com/docs/4.1/content/tables/#responsive-tables
> Make table responsive

- src/Platform/Http/Controllers/Systems/RelationController.php
This fixes Relation scope not working
**Code**
`Relation::make('chief.')->fromModel(User::class, 'name')->applyScope('bureau')`
**Expected behavior**
Getting results and can search results
**Actual behavior**
Getting no results and doing a search results in :
`Cannot use object of type Illuminate\Database\Query\Builder as array`
> Fix scope not working in Relation

- resources/views/layouts/table.blade.php
- src/Screen/Layouts/Table.php
In table layout:
Default false.
> The ability to make the table striped

- resources/js/controllers/layouts/form_controller.js
> refs #984 [Screen] Fixed problem send form by "Enter"

- resources/js/controllers/fields/input_controller.js
> :bug: fix masked input. This closes #982

- src/Setting/Setting.php
- tests/Unit/SettingsTest.php
> refs #1004 [Setting] Fixed string type default value

- src/Screen/Fields/Relation.php
...when value is not iterable for the fromCass method
> Fix issue with the relation 

- src/Screen/Layout.php
Added ability to quickly create tables.
```php
Layout::table('clients', [
TD::set('name', __('Name')),
TD::set('created_at', __('Created'))->sort(),
]),
```
- Add a new method to layout class
> Added a short record to create a table

- resources/views/layouts/table.blade.php
- Remove 2 symbols from file
- ~~Make table great again!~~
> Make table responsive on large screen

- src/Screen/Fields/Relation.php
- Add max method
Question:
But i think this method also need to be in Select class, what you think about it? we need to create some trait for select fields?
Thanks...
> Set the maximum number of items in relation select

- resources/views/fields/picture.blade.php
- Add btn-group to buttons of the picture field like the cropper field
> Fixed picture field buttons layout

- install-stubs/Orchid/Screens/PlatformScreen.php
@tabuna requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/orchidsoftware/platform/
> Scrutinizer Auto-Fixes

- composer.json
- src/Platform/Commands/InstallCommand.php
- src/Platform/Commands/LinkCommand.php
- src/Platform/Http/Controllers/Systems/ResourceController.php
- src/Platform/Providers/FoundationServiceProvider.php
- src/Platform/Updates.php
- src/Presets/Orchid.php
- src/Presets/Source.php
- tests/Console/ArtisanTest.php
- tests/Feature/Platform/AuthTest.php
- tests/Feature/Platform/RelationsTest.php
> Support Laravel 7.0

- src/Platform/Providers/FoundationServiceProvider.php
- Add more freedom to published migrations, for example - renaming.
> [7.0] Add the ability to change default migrations

- CHANGELOG.md
- src/Platform/Dashboard.php
- src/Platform/Http/Middleware/TurbolinksLocation.php
- tests/Unit/TurbolinksLocationTest.php
> ## 7.1.2 - 2020-04-26

- src/Access/RoleAccess.php
- src/Access/RoleInterface.php
- tests/Feature/Example/RoleTest.php
It is now possible to use non numeric values as role id
> removed typehinting from role id

- CHANGELOG.md
- src/Platform/Dashboard.php
- src/Screen/Fields/Relation.php
- src/Support/Assert.php
- tests/Unit/Screen/Fields/RelationTest.php
> Support for string primary models in relations field

- resources/views/layouts/columns.blade.php
- Add space between Columns Layout
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Add more space between columns

- install-stubs/Orchid/Presenters/UserPresenter.php
- tests/Unit/Platform/UserTest.php
I know this is a minor thing and users can easily customize this but still I think this is a cool default
roles as default subtitle for userpresenter
> print roles as default user subtitle

- resources/js/controllers/fields/relation_controller.js
- resources/js/controllers/fields/select_controller.js
> Fix select2 cache destroy

- install-stubs/Orchid/Screens/Examples/ExampleChartsScreen.php
- install-stubs/Orchid/Screens/Examples/ExampleScreen.php
- install-stubs/Orchid/Screens/PlatformScreen.php
- install-stubs/Orchid/Screens/User/UserListScreen.php
- src/Platform/Commands/AdminCommand.php
- src/Screen/Contracts/Fieldable.php
> [8.0] fix docblocks

- src/Screen/Layout.php
> Fix docblock for the moved file

- config/platform.php
- resources/views/auth/signin.blade.php
- routes/auth.php
This PR will allow users to switch off (or on) reset password functionality in built-in authentication mechanism.
In addition, comments in config files were updated.
> Add configuration option to switch on/off reset password functionality

- resources/js/controllers/fields/picture_controller.js
- resources/views/fields/picture.blade.php
- src/Screen/Fields/Picture.php
> Добавлен атрибут "group" для поля "picture"

- install-stubs/Orchid/Layouts/Examples/ChartBarExample.php
- install-stubs/Orchid/Layouts/Examples/ChartLineExample.php
- install-stubs/Orchid/Screens/Examples/ExampleFieldsAdvancedScreen.php
- Removed height declaration from default charts
- Replaced the outdated group definition with the actual
> Static analyzer

- src/Platform/Commands/AdminCommand.php
- Removed unused constructor code
> Removed unused constructor code

- resources/views/fields/matrix.blade.php
- src/Screen/Fields/Matrix.php
> refs #1201 Fixed index calculation instead of quantity

- CHANGELOG.md
- resources/views/layouts/table.blade.php
- resources/views/partials/layouts/td.blade.php
- resources/views/partials/layouts/th.blade.php
- src/Platform/Dashboard.php
- src/Screen/Layouts/Table.php
- src/Screen/TD.php
- tests/App/Layouts/TotalTable.php
- tests/Unit/Screen/Layouts/TableTest.php
> [7.18.0] Added a row with totals to the table

- src/Metrics/Chartable.php
- src/Screen/Screen.php
- tests/App/ExemplarServiceProvider.php
- tests/App/Screens/MethodsResponseScreen.php
- tests/Feature/App/MethodsResponseScreenTest.php
> [8.1] refs #1221 Added backtracking in default screen methods.

- stubs/app/Orchid/Filters/RoleFilter.php
Fixed the role selection field and added an example of displaying a value.
> [8.1] Supplemented example filter

- CHANGELOG.md
- src/Platform/Commands/PresenterCommand.php
- src/Platform/Providers/FoundationServiceProvider.php
- stubs/presenter.stub
- tests/Console/ArtisanTest.php
Added a command to create a presenter
```php
artisan orchid:presenter PostPresenter
```
> Added a command to create a presenter

- src/Screen/Field.php
- tests/Unit/Screen/Fields/InputTest.php
> refs #1240 Allow data attributes

- resources/js/controllers/fields/select_controller.js
- src/Screen/Fields/Select.php
> add taggable option for select

- resources/js/controllers/fields/select_controller.js
Fixes #
- remove ! operator
-
-
> fix compare operator for hasAttribute

- src/Platform/Http/Middleware/Access.php
This change adds a new check for the presence of some routes. The primary use is when the application login form is disabled. Then, when you try to access the secure page, an exception will be thrown with the message that the route was not found.
Now there will be a sequential check of several route names at once:
```bash
`platform.login` -> `login` -> 401
```
As a result, when you disable the option in the config and install one of the proposed packages for authorization, you will be automatically redirected to the login form.
> Redirects when the login form is disabled

- CHANGELOG.md
- src/Platform/Dashboard.php
- src/Platform/Providers/FoundationServiceProvider.php
> ## 9.0.3 - 2020-10-02

- CHANGELOG.md
- resources/views/layouts/tabs.blade.php
- src/Platform/Dashboard.php
- Removed white wrapper for tabs elements
> Removed white wrapper for tabs elements

- resources/views/app.blade.php
- resources/views/dashboard.blade.php
- resources/views/layouts/base.blade.php
- resources/views/layouts/pagination.blade.php
- resources/views/layouts/selection.blade.php
- resources/views/layouts/table.blade.php
- Fixed `ob_*` behavior when using the Blade in PHPUnit tests
- Removed optional tags
- Removed dash when a description is empty
> Blade problem

- CHANGELOG.md
- src/Platform/Dashboard.php
- src/Screen/Field.php
- src/Screen/Fields/Upload.php
- tests/Unit/Screen/Fields/InputTest.php
> refs #1313 Escape inline attributes

- resources/views/app.blade.php
> Scaling on iOS

- resources/views/layouts/table.blade.php
- src/Screen/Layouts/Table.php
- Add bootstrap table-bordered to table layout
> Add bootstrap table-bordered

- src/Screen/Layouts/Table.php
- tests/Unit/Screen/Layouts/TableTest.php
> Added tests for table

- CHANGELOG.md
- src/Screen/Action.php
- Automatically translate button names
> ## 9.7.0 - 2020-10-24

- resources/lang/ru.json
- resources/views/partials/confirm.blade.php
- Fixed typo in the first character of the cancel button in `confirm` view, Russian character instead of English
- Added missed key in Russian translation
> Fixed translation

- composer.json
- Added funding in the composer config
> Added funding

- resources/js/controllers/fields/relation_controller.js
- resources/views/fields/relation.blade.php
- src/Platform/Http/Controllers/Systems/RelationController.php
- src/Platform/Http/Requests/RelationRequest.php
- src/Screen/Fields/Relation.php
- tests/Feature/Platform/RelationsTest.php
- tests/Unit/Screen/Fields/RelationTest.php
Multiple columns for search in Relation field
```php
Relation::make('customer_id')
->fromModel(Customer::class, 'name', 'id')
->searchColumns('company','tin')
```
> Search columns for Relation field

- resources/js/controllers/fields/radiobutton_controller.js
Fixes #
- Fxed display of the active radio button
> :bug: fixed display of the active radio button

- resources/views/layouts/filter.blade.php
> fixed filters style

- .github/workflows/phpunit.yml
- composer.json
- src/Screen/Screen.php
> Support PHP 8.0

- .github/workflows/coverage.yml
- .github/workflows/php-cs-fixer.yml
- .github/workflows/phpunit.yml
- .gitignore
- .php_cs.dist
- src/Support/Init.php
- Actions for style code fixer
> Added action for style fixer

- CHANGELOG.md
- src/Platform/Dashboard.php
- src/Screen/Layouts/Selection.php
- tests/App/Filters/HiddenFilter.php
- tests/Unit/Screen/Layouts/SelectionTest.php
- Fixed bug when trying to display only hidden filter
> Fixed bug when trying to display only hidden filter

- CHANGELOG.md
- src/Platform/Dashboard.php
- src/Screen/Layouts/Selection.php
> Fixed display hidden filter

- resources/lang/de.json
- resources/lang/es.json
- resources/lang/fa.json
- resources/lang/fr.json
- resources/lang/pt.json
- resources/lang/ru.json
- resources/lang/uk.json
- resources/views/dashboard.blade.php
- Rename `Go to top` to `Scroll to top`
> Improve UX of Main Navigation: "Scroll to top" Link

- resources/js/controllers/fields/datetime_controller.js
- resources/sass/plugins/plugin.scss
- resources/views/partials/filters/date.blade.php
- src/Screen/Fields/DateTimer.php
Fixes #1386
- FlatDatePicker config change to set `static: true`
- `.flatpickr-wrapper` class given 100% width
- date filter markup changed to include js stoppropogation to stop the datepicker closing when next/back month buttons are clicked
> Fix datepicker issue on filter dropdown

- stubs/app/Orchid/Screens/User/UserProfileScreen.php
- Fixed wrong method to process password update form.
> Fixed password update on profile page

- resources/lang/fr.json
> Updated "Systemes" (plural) to "Système" (singular)

- resources/lang/pt.json
> Updated "Sistemas" (plural) to "Sistema" (singular)

- readme.md
> Optimized/Extended README.md

- readme.md
- Optimized/Extended README.md (#1502)
> Promo patch

- readme.md
Fixed various smaller spelling mistakes
Shortened feature-descriptions and linked the most important parts
> Spelling mistakes, optimized feature-texts

- readme.md
> Grammar improvements

- readme.md
Validate by Grammarly
Used the same color for thumbs up like for thank you Emoji
Used Emoji's to keep symbol usage consistent
Small optimization in the documentation section
> Fixed spelling mistakes/grammatical errors

- CHANGELOG.md
- src/Metrics/TimeCollection.php
- src/Platform/Dashboard.php
- tests/Unit/MetricsTest.php
- Added Method for display the day of the week in charts
> Added method for display the day of the week in charts

- CHANGELOG.md
- src/Screen/TD.php
- src/Support/Blade.php
- tests/App/Components/ClosureComponent.php
- tests/App/Components/EmptyComponent.php
- tests/App/Components/HtmlableComponent.php
- tests/App/Components/UserTD.php
- tests/App/Components/UserTDArguments.php
- tests/App/Components/UserTDView.php
- tests/App/Views/components/user-td-view.blade.php
- tests/Unit/Screen/TDComponentTest.php
- tests/Unit/Support/BladeComponentTest.php
- Method for using the component in TD #1489
> Method for using the component in TD

- readme.md
Link to "release early, release often" added this explains dev philosophy
Release strategy explained
Underlined that structured feedback is important
Added additional emoji that celebrates that Orchid is free
> Reference to changelog included

- resources/lang/es.json
- resources/lang/ru.json
- stubs/app/Orchid/Layouts/User/ProfilePasswordLayout.php
- stubs/app/Orchid/Layouts/User/UserPasswordLayout.php
- stubs/app/Orchid/Screens/User/UserEditScreen.php
- stubs/app/Orchid/Screens/User/UserListScreen.php
- stubs/app/Orchid/Screens/User/UserProfileScreen.php
- stubs/app/routes/platform.php
- tests/Feature/Example/UserTest.php
This is implementation for issue #1527
Add ability to create new user via Users admin screen.
> Create new user via Systems -> Users screen

- resources/lang/ru.json
Added keys with the Russian translation in ru.json that don't have a translation yet
> Added missing keys for Russian locale

- src/Screen/AsSource.php
- tests/Unit/Screen/SourceTest.php
Fixes #1558
- Support virtual fields
> refs #1558 [AsSource] Support virtual fields

- src/Screen/Concerns/Makeable.php
Fixes #
- small type mismatch in Makeable.php
> fix small type mismatch

- resources/views/layouts/selection.blade.php
When the page was refreshed, filters might not be sent.
> refs #1152 Fix error with filter after page refresh

- resources/views/partials/fields/matrixRow.blade.php
- src/Screen/Fields/Matrix.php
- tests/Unit/Screen/Fields/MatrixTest.php
Fixes #1617 
Add idPrefix attribute for matrix
> fix #1617 add IdPrefix

- CHANGELOG.md
- src/Metrics/TimeCollection.php
- src/Platform/Dashboard.php
- Translated missing text in Italian [#1653](https://github.com/orchidsoftware/platform/pull/1653)
- Method `showMinDaysOfWeek` for `TimeCollection`
> ## 9.21.0 - 2021-04-10

- src/Platform/Dashboard.php
https://laravel.com/docs/8.x/collections#method-sort
> If your sorting needs are more advanced, you may pass a callback to `sort` with your own algorithm. Refer to the PHP documentation on `uasort`, which is what the collection's `sort` method calls utilizes internally.
> Fix menu sorting

- CHANGELOG.md
- src/Platform/Dashboard.php
- Sorting of elements menu [#1668](https://github.com/orchidsoftware/platform/pull/1668)
> ## 10.0.1 - 2021-04-15

- resources/views/partials/filters/date.blade.php
- src/Screen/Fields/DateTimer.php
Убран забытый namespace `fields--`
> fix datetime field

- CHANGELOG.md
- src/Platform/Dashboard.php
- Make submenu id equal to the slug [#1673](https://github.com/orchidsoftware/platform/pull/1673)
- Remove namespace for `Date` field [#1672](https://github.com/orchidsoftware/platform/pull/1672)
> 10.0.2 - 2021-04-17

- resources/views/layouts/filter.blade.php
> Add bottom padding for best view

- resources/views/layouts/table.blade.php
- src/Screen/Layouts/Table.php
- Add optional title to tables
> adding title property to Table

- resources/views/components/notification.blade.php
Fixes #
data-notification-interval="{{ config('platform.notifications.interval') }}"
-
-
-
> read notifications interval from config

- src/Platform/OrchidServiceProvider.php
Fixes #
- Fix the menu state while using laravel octane
- Just check if the menu if filled before filling it again
> Fix the menu state while using laravel octane

- src/Screen/Actions/Menu.php
- tests/Unit/Screen/Actions/MenuTest.php
I added possibility to pass array in method permission facade Menu
> ref issue_1799 change arguments in method permission Menu facade

- resources/js/controllers/map_controller.js
Fixes #
https://stackoverflow.com/questions/36246815/data-toggle-tab-does-not-download-leaflet-map/36257493#36257493
> fix(map): fix tab toggle with leaflet map

- resources/views/layouts/modal.blade.php
Just change place for attribute {{type}} .
> ref issue_1829 change place where modal-size class outputs

- resources/views/app.blade.php
Added a class to body, that will always use a slugified version of the current path as basic.
This allows to style subpages (login, template, ...) differently easily using a custom css file.
> Added routeprefixed class to body

- src/Screen/Actions/Menu.php
> menu slug translate

- .github/workflows/phpunit.yml
- composer.json
- tests/Unit/MetricsTest.php
> Support PHP 8.1

- .github/workflows/coverage.yml
- .github/workflows/phpunit.yml
Update version for `actions/checkout` and `actions/cache`
> Update workflows GitHub Action

- resources/js/controllers/cropper_controller.js
- resources/js/controllers/picture_controller.js
- resources/views/fields/cropper.blade.php
- resources/views/fields/picture.blade.php
- src/Screen/Fields/Cropper.php
- src/Screen/Fields/Picture.php
Adds the accepted method to both picture and cropper to control uploadable mime
> add accepted-files to cropper and picture

- resources/views/fields/radiobutton.blade.php
Fixes #
- Unique id for radio button
> Solve Radio buttons id duplicated

- resources/sass/core/tables.scss
- resources/views/layouts/table.blade.php
- src/Screen/Layouts/Table.php
Adding compact Table layout (compact bootstrap table)
> Adding compact option to Table layout

- resources/js/controllers/popover_controller.js
Fixes 
Destroy popover on disconnect
- Update popover_controller.js
> Destroy popover on disconnect

- src/Screen/Screen.php
It is possible, in user-defined screen, to render a different view than default
> Ability to override default view

- resources/views/partials/fields/matrixRow.blade.php
- src/Screen/Fields/Matrix.php
- Sometimes matrix could be use to update data but not remove it, so should it exist the option to disable the default trash button in every row.
> Add variable to make remove rows optional in matrix field

- resources/js/controllers/quill_controller.js
- resources/views/fields/quill.blade.php
- src/Screen/Fields/Quill.php
This attribute allows you to group uploaded files through Quill
> Added attribute 'groups' to quill

- resources/views/layouts/table.blade.php
- src/Screen/Cell.php
- src/Screen/TD.php
- tests/Unit/Screen/Layouts/TableTest.php
```php
TD::make()->render(function (Model $model, object $loop) {
return $loop->index;
})
```
> Add a second $loop parameter to the closure function

- resources/sass/plugins/select2.scss
> Reset select 2 position in RTL

- resources/js/controllers/relation_controller.js
- resources/js/controllers/select_controller.js
> select2 adding dir option

- resources/views/partials/confirm.blade.php
> Fix deprecation

- src/Screen/Cell.php
- src/Screen/Layouts/Component.php
- src/Support/Blade.php
- tests/App/Views/components/simple-anonymous-component.blade.php
- tests/Unit/Screen/Layouts/ComponentTest.php
- tests/Unit/Screen/TDComponentAsValueTest.php
- tests/Unit/Screen/TDComponentTest.php
- tests/Unit/Support/BladeComponentTest.php
- Possibility to use anonymous components and class based components by aliases
- Possibility to pass additional parameters to Layout::component('component')->with($addon), where addon has more priority then Repository data
> ref #2324 anonymous components

- resources/views/layouts/metric.blade.php
https://user-images.githubusercontent.com/5102591/182895146-040ec506-a27a-4d48-b3c1-299c44f6e3a0.mp4
> Change metrics view

- config/platform.php
- resources/views/fields/cropper.blade.php
- resources/views/fields/picture.blade.php
- resources/views/fields/upload.blade.php
Fixes [#2329](https://github.com/orchidsoftware/platform/issues/2329)
- fix: set default storage disk as defined in config file
> fix: set default storage from config

- src/Screen/Field.php
- src/Screen/Fields/Radio.php
- For radio inputs we shouldn't overwrite value with old data.
- We should add **checked** attribute if oldValue === radio value.
> Don't overwrite radio value

- resources/js/controllers/checkbox_controller.js
> refs #2298 Fixed nullable element

- src/Screen/TD.php
Add new feature for filter 
So now have a change to add custom label or placeholder for table column, after filtered))
> add display custom filter value

- resources/js/controllers/upload_controller.js
- src/Platform/Http/Controllers/AttachmentController.php
Added filtering by the group parameter from the request to the media method
> Add available to filter attachments in media by group

- resources/js/controllers/tabs_controller.js
Issue https://github.com/orchidsoftware/platform/issues/2443
> Fix pagination in tabs

- tests/Feature/Platform/GuardAuthTest.php
- tests/Unit/Screen/Fields/BaseFieldTest.php
- tests/Unit/Screen/Fields/RelationTest.php
- tests/Unit/Screen/Fields/SelectTest.php
- tests/Unit/Screen/RepositoryTest.php
This pull request contains changes for upgrading to [PHPUnit 9](https://phpunit.de/announcements/phpunit-9.html) automated by the [PHPUnit 9 Shift](https://laravelshift.com/upgrade-phpunit-9).
**Before merging**, you should **review all comments** and commit any changes to the `shift-75072` branch.
If there were changes you felt could have been automated, please reply to the follow-up email with your feedback or on [Twitter](https://twitter.com/laravelshift).
> PHPUnit 9 Shift

- src/Platform/Notifications/DashboardMessage.php
> Fixed Bug: enums have no default serialization

- stubs/app/Orchid/Screens/User/UserProfileScreen.php
Fixes #
- Add validation to new password in change password feature. The new password should be different than old password.
> New Password Validation

- src/Filters/Types/Ilike.php
> Create Ilike Filter Type

- resources/views/workspace/compact.blade.php
Ability to override footer in compact workspace template.
> Added ability to override footer in compact workspace template

- src/Screen/Layouts/Table.php
- Adds CursorPaginator support for Table Layout
- Change type hintings for `hasHeader()` to support contracts not specified classes
> Add CursorPaginator for Table Layout

- resources/views/partials/fields/matrixRow.blade.php
- Added translation of the delete row button in the "matrix" field.
> Added translation of the delete row button in the "matrix" field.

- resources/js/controllers/picture_controller.js
- resources/views/fields/picture.blade.php
FIx (https://github.com/orchidsoftware/platform/issues/2664)
> Can't upload the same image twice #2664

- src/Screen/Fields/Select.php
- tests/Unit/Screen/Fields/SelectTest.php
- Select from enum feature. Supports both backed enum and not backed. Throws exception if provided not enum. Render the right value
> Select from enum feature

- src/Screen/Screen.php
Fixes #
fix extractState when state is null
> fix extractState when state is null

- resources/views/layouts/table.blade.php
Fixes #
- add code && $rows->isNotEmpty()
-
-
> Fix $total to hide when $rows->isEmpty

- resources/views/layouts/block.blade.php
> Checking for block output with title and description

- resources/js/controllers/datetime_controller.js
- src/Screen/Fields/DateTimer.php
- tests/Unit/Screen/Fields/DateTimerTest.php
Fixes #
-  DateTimer format24hr() doesn't work
-
-
> Fixed: DateTimer format24hr() doesn't work #2742

- resources/views/fields/matrix.blade.php
- src/Screen/Fields/Matrix.php
Added a possibility to change 'Add row' label for matrix field.
Small feature, just to avoid publish view for one line
> Added a possibility to change 'Add row' label for matrix field

- resources/js/controllers/relation_controller.js
- src/Platform/Http/Controllers/RelationController.php
- tests/Feature/Platform/RelationsTest.php
> Preserve Relation field query order

- resources/lang/ru.json
Fixes #
- translated Role edit title and description in ru language
> Translated Role edit title and description in ru language

- src/Platform/Http/Controllers/LoginController.php
- tests/Browser/LoginTest.php
- tests/Feature/Platform/AuthTest.php
> Fixed dusk authorization tests supporting laravel 10 and 11

- resources/js/controllers/cropper_controller.js
- resources/views/fields/cropper.blade.php
- src/Screen/Fields/Cropper.php
Adding smoothing settings for Cropper
> Adding smoothing settings for Cropper

- src/Screen/Fields/DateRange.php
Adding methods format/serverFormat for DateRange
Fixes #
-
-
-
> DateRange add methods format/serverFormat

- stubs/field.stub
Fixes #
- added required attribute name to inlineAttributes
> fixed stub
